### ISSUE TITLE
this pacakge not comptiable with asp.net core3.0 

### ISSUE THREAD

**Issue by lixiandai** [dotarj/PartialResponse.AspNetCore.Mvc.Formatters.Json#11]
Any plan to upgrade the package to support asp.net core 3.0?

**Comment by kunal-saini** [comment]
@lixiandai probably a workaround here: https://github.com/SuperKunal/PartialResponse.AspNetCore.Mvc.Formatters.Json

**Comment by dotarj** [comment]
I made a branch for compatibility with netcoreapp3.0 (#12). The code works but there are some problems with the AppVeyor build which I have to solve first.

**Comment by dotarj** [comment]
Version 5.1.0 with support for ASP.NET Core 3.0 has just been [released](https://github.com/dotarj/PartialResponse.AspNetCore.Mvc.Formatters.Json/releases/tag/5.1.0).
